const games={battle:['⚔️ Battle Brains','Math-powered combat'],hospital:['🩺 Math Hospital','Save patients under pressure'],builder:['🧩 Brain Builders','Pattern puzzles'],tetris:['🧱 Math Tetris','Stack, rotate, clear'],board:['🎲 Quest Board','Explore the dungeon'],racer:['🏎️ Math Racers','Beat the rival']};
let current='',score=0,round=0,total=5,xp=0,coins=120,combo=0,keys={},raf=0,gameState=null;const $=s=>document.querySelector(s);
function start(g){document.onkeydown=null;document.onkeyup=null;current=g;score=0;round=0;combo=0;if(document.querySelector('#combo'))document.querySelector('#combo').textContent=0;cancelAnimationFrame(raf);$('#backdrop').classList.add('open');if(['tetris','board','racer'].includes(g))return actionSetup();mathSetup()}
function shell(title,body){$('#gameView').innerHTML=`<p class="eyebrow">${title}</p>${body}`}
function mathSetup(){shell(games[current][0],`<h2>${games[current][1]}</h2><label class="question-count">Questions per quest <select id="count"><option value="5">5 · Quick run</option><option value="10">10 · Full quest</option><option value="20">20 · Legend mode</option></select></label><button class="primary" id="begin">Start quest →</button>`);$('#begin').onclick=()=>{total=+$('#count').value;nextQuestion()}}
function problem(){const level=Math.min(4,1+Math.floor(round/5)),type=Math.floor(Math.random()*4),n=()=>Math.floor(Math.random()*(7+level*3))+2;if(type===0){const x=n(),y=n();return {text:`Solve: ${x}x + ${y} = ${x*3+y}`,answer:x*3}}if(type===1){const b=n(),p=2+Math.floor(Math.random()*2);return {text:`${b}^${p} = ?`,answer:b**p}}if(type===2){const pct=[10,20,25,50,75][Math.floor(Math.random()*5)],v=[40,60,80,120,200][Math.floor(Math.random()*5)];return {text:`${pct}% of ${v} = ?`,answer:pct*v/100}}const a=n(),b=n();return {text:`${a}² − ${b}² = ?`,answer:a*a-b*b}}
function nextQuestion(){const p=problem(),opts=[p.answer,p.answer+2,Math.max(1,p.answer-3),p.answer+7].sort(()=>Math.random()-.5);shell(games[current][0],`<h2>${games[current][1]}</h2><p>Round ${round+1} of ${total} · Score ${score}</p><div class="question">${p.text}</div><div class="answers">${opts.map(x=>`<button class="answer" data-x="${x}" data-a="${p.answer}">${x}</button>`).join('')}</div><p class="keyboard-hint">⌨️ W A S D chooses an answer</p>`);document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(+b.dataset.x,+b.dataset.a))}
function answer(x,a){if(x!==a){score=Math.max(0,score-1);combo=0;document.querySelector('#combo').textContent=combo;toast('Incorrect · combo reset');round++;return setTimeout(()=>round>=total?finish():nextQuestion(),430)}score++;combo++;document.querySelector('#combo').textContent=combo;const multiplier=Math.min(4,1+Math.floor(combo/3));xp+=20*multiplier;coins+=5*multiplier;$('#xp').textContent=xp;$('#coins').textContent=coins;if(current==='battle')return chooseAttack();toast('Correct · x'+multiplier+' reward combo ✨');round++;setTimeout(()=>round>=total?finish():nextQuestion(),430)}
function chooseAttack(){shell('⚔️ ABILITY READY',`<h2>Choose your attack</h2><div class="scene battle-scene" id="battleArena"><span class="hero-fighter">🧙</span><span class="enemy">👾</span></div><div class="answers"><button class="answer ability" data-spell="fire">1 · 🔥 Fireball</button><button class="answer ability" data-spell="bolt">2 · ⚡ Thunderbolt</button><button class="answer ability" data-spell="wind">3 · 🌪️ Cyclone</button><button class="answer ability" data-spell="shield">4 · 🛡️ Shield Bash</button></div><p class="keyboard-hint">⌨️ Press 1–4 or click an ability · Space = dodge</p>`);document.querySelectorAll('.ability').forEach(b=>b.onclick=()=>cast(b.dataset.spell,b.textContent));document.onkeydown=e=>{const map={'1':'fire','2':'bolt','3':'wind','4':'shield'};if(map[e.key])cast(map[e.key],document.querySelector(`[data-spell="${map[e.key]}"]`).textContent);if(e.code==='Space')toast('Perfect dodge! +10 style points ✨')}}
function cast(spell,label){const arena=$('#battleArena');if(!arena||arena.classList.contains('cast'))return;arena.classList.add('cast',`spell-${spell}`);toast(label+' launched!');setTimeout(()=>{const enemy=arena.querySelector('.enemy');enemy.classList.add('enemy-hit');coins+=20;$('#coins').textContent=coins;toast('Monster defeated! +20 coins 💥');round++;setTimeout(()=>{document.onkeydown=null;round>=total?finish():nextQuestion()},650)},650)}
function finish(){shell('QUEST COMPLETE',`<div class="result"><div class="big">🏆</div><h2>Nice run!</h2><p>You scored <b>${score}/${total}</b> · +${score*20} XP</p><button class="primary" id="again">Play again →</button></div>`);$('#again').onclick=()=>start(current)}
function actionSetup(){const help=current==='racer'?'W accelerates · A/D steer · S brakes':current==='tetris'?'A/D move · W rotate · S drop':'W/A/S/D move through the map';shell(games[current][0],`<h2>${games[current][1]}</h2><canvas id="gameCanvas" width="560" height="300"></canvas><p class="keyboard-hint">⌨️ ${help}</p><button class="primary" id="go">Start game →</button>`);$('#go').onclick=()=>{gameState={x:60,y:240,t:0,won:false,blocks:[],piece:{x:4,y:0,rot:0}};$('#go').remove();keys={};document.onkeydown=e=>{keys[e.key.toLowerCase()]=true;e.preventDefault()};document.onkeyup=e=>keys[e.key.toLowerCase()]=false;raf=requestAnimationFrame(loop)}}
function loop(){const c=$('#gameCanvas'),ctx=c.getContext('2d');gameState.t++;ctx.clearRect(0,0,c.width,c.height);if(current==='racer')race(ctx);else if(current==='board')board(ctx);else tetris(ctx);if(!gameState.won)raf=requestAnimationFrame(loop)}
function race(ctx){ctx.fillStyle='#1c2845';ctx.fillRect(0,0,560,300);ctx.fillStyle='#4d5560';ctx.fillRect(80,0,400,300);ctx.strokeStyle='#fff';ctx.setLineDash([22,20]);ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(280,0);ctx.lineTo(280,300);ctx.stroke();ctx.setLineDash([]);gameState.x+=keys.d?3:keys.a?-3:0;gameState.x=Math.max(95,Math.min(445,gameState.x));gameState.y-=keys.w?2.5:keys.s?-1:0;ctx.font='42px serif';ctx.fillText('🏎️',gameState.x,gameState.y);ctx.fillText('🏁',500,45);ctx.fillStyle='#ff6b5e';ctx.fillRect(18,18,120,12);ctx.fillStyle='#c9f05a';ctx.fillRect(18,18,Math.min(120,gameState.t/8),12);if(gameState.y<35){win('🏁 Finish line!')}}
function board(ctx){ctx.fillStyle='#d9b879';ctx.fillRect(0,0,560,300);ctx.strokeStyle='#86633a';for(let x=0;x<560;x+=56){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,300);ctx.stroke()}for(let y=0;y<300;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(560,y);ctx.stroke()}if(keys.a)gameState.x-=3;if(keys.d)gameState.x+=3;if(keys.w)gameState.y-=3;if(keys.s)gameState.y+=3;gameState.x=Math.max(20,Math.min(530,gameState.x));gameState.y=Math.max(25,Math.min(280,gameState.y));ctx.font='36px serif';ctx.fillText('🧙',gameState.x,gameState.y);ctx.fillText('👾',270,145);ctx.fillText('🏆',500,270);if(gameState.x>470&&gameState.y>230)win('🎁 Treasure found!')}
function tetris(ctx){ctx.fillStyle='#101b38';ctx.fillRect(0,0,560,300);const size=18,ox=190,oy=10;ctx.strokeStyle='#364266';for(let x=0;x<10;x++)for(let y=0;y<15;y++)ctx.strokeRect(ox+x*size,oy+y*size,size,size);if(gameState.t%8===0)gameState.piece.y++;if(keys.a)gameState.piece.x=Math.max(0,gameState.piece.x-1);if(keys.d)gameState.piece.x=Math.min(9,gameState.piece.x+1);if(keys.s)gameState.piece.y=Math.min(14,gameState.piece.y+1);if(keys.w)gameState.piece.rot=(gameState.piece.rot+1)%4;ctx.font='19px serif';ctx.fillText(['🟦','🟨','🟥','🟩'][gameState.piece.rot],ox+gameState.piece.x*size,oy+gameState.piece.y*size+17);ctx.fillStyle='#c9f05a';ctx.font='16px Arial';ctx.fillText('Clear 10 rows to win',18,35);if(gameState.piece.y>=14)win('🧱 Stack complete!')}
function win(msg){gameState.won=true;combo++;if(document.querySelector('#combo'))document.querySelector('#combo').textContent=combo;cancelAnimationFrame(raf);const multiplier=Math.min(4,1+Math.floor(combo/3));xp+=40*multiplier;coins+=20*multiplier;$('#xp').textContent=xp;$('#coins').textContent=coins;toast(msg+' + rewards');setTimeout(()=>shell('LEVEL COMPLETE',`<div class="result"><div class="big">🏆</div><h2>${msg}</h2><button class="primary" id="again">Play again →</button></div>`)||($('#again').onclick=()=>start(current)),700)}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',1300)}
document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>start(b.dataset.game));$('#close').onclick=()=>{$('#backdrop').classList.remove('open');cancelAnimationFrame(raf);document.onkeydown=null;document.onkeyup=null};
document.addEventListener('keydown',e=>{if(!$('#backdrop').classList.contains('open')||document.onkeydown)return;const map={w:0,a:1,s:2,d:3},bs=[...document.querySelectorAll('.answer')];if(map[e.key.toLowerCase()]!==undefined&&bs[map[e.key.toLowerCase()]])bs[map[e.key.toLowerCase()]].click()});


let currentAvatar=localStorage.getItem('mqAvatar')||'🧑‍🚀';const avatarStage=document.querySelector('#avatarStage');if(avatarStage)avatarStage.textContent=currentAvatar;document.querySelectorAll('[data-avatar]').forEach(b=>b.onclick=()=>{currentAvatar=b.dataset.avatar;localStorage.setItem('mqAvatar',currentAvatar);if(avatarStage)avatarStage.textContent=currentAvatar});





document.querySelector('#dailyReward')?.addEventListener('click',()=>{const today=new Date().toDateString();if(localStorage.getItem('mqReward')!==today){coins+=50;xp+=50;localStorage.setItem('mqReward',today);document.querySelector('#coins').textContent=coins;document.querySelector('#xp').textContent=xp;toast('Daily reward claimed! +50 coins +50 XP 🎁')}else toast('Daily reward already claimed — come back tomorrow!')});

