const games={battle:['⚔️ Battle Brains','Math-powered combat'],hospital:['🩺 Math Hospital','Save patients under pressure'],builder:['🧩 Brain Builders','Pattern puzzles'],tetris:['🧱 Math Tetris','Stack, rotate, clear'],board:['🎲 Quest Board','Explore the dungeon'],racer:['🏎️ Math Racers','Beat the rival']};
let current='',score=0,round=0,total=5,xp=Number(localStorage.getItem('mqXp')||0),coins=Number(localStorage.getItem('mqCoins')||120),combo=0,keys={},raf=0,gameState=null;const $=s=>document.querySelector(s);
function start(g){document.onkeydown=null;document.onkeyup=null;current=g;score=0;round=0;combo=0;if(document.querySelector('#combo'))document.querySelector('#combo').textContent=0;cancelAnimationFrame(raf);$('#backdrop').classList.add('open');if(['tetris','board','racer'].includes(g))return actionSetup();mathSetup()}
function shell(title,body){$('#gameView').innerHTML=`<p class="eyebrow">${title}</p>${body}`}
function mathSetup(){shell(games[current][0],`<h2>${games[current][1]}</h2><label class="question-count">Questions per quest <select id="count"><option value="5">5 · Quick run</option><option value="10">10 · Full quest</option><option value="20">20 · Legend mode</option></select></label><button class="primary" id="begin">Start quest →</button>`);$('#begin').onclick=()=>{total=+$('#count').value;nextQuestion()}}
function problem(){const level=Math.min(4,1+Math.floor(round/5)),n=()=>Math.floor(Math.random()*(7+level*3))+2,type=Math.floor(Math.random()*6);if(type===0){const a=n(),x=Math.floor(Math.random()*9)+2,b=n(),c=a*x+b;return {text:`Solve: ${a}x + ${b} = ${c}`,answer:x,hint:`Subtract ${b}, then divide by ${a}.`}}if(type===1){const a=n(),x=Math.floor(Math.random()*7)+2,b=Math.floor(Math.random()*5)+1,c=a*(x+b);return {text:`Solve: ${a}(x + ${b}) = ${c}`,answer:x,hint:`Divide by ${a}, then subtract ${b}.`}}if(type===2){const b=n(),p=2+Math.floor(Math.random()*2);return {text:`Evaluate: ${b}^${p}`,answer:b**p,hint:`Multiply ${b} by itself ${p} times.`}}if(type===3){const pct=[10,20,25,50,75][Math.floor(Math.random()*5)],v=[40,60,80,120,200][Math.floor(Math.random()*5)];return {text:`Find ${pct}% of ${v}`,answer:pct*v/100,hint:`Convert ${pct}% to a decimal, then multiply by ${v}.`}}if(type===4){const m=n(),x=Math.floor(Math.random()*6)+2,b=n(),c=m*x+b;return {text:`If y = ${m}x + ${b}, find y when x = ${x}`,answer:c,hint:`Substitute ${x} for x.`}}const a=n(),b=n();return {text:`Use difference of squares: ${a}² − ${b}²`,answer:a*a-b*b,hint:`Compute ${a}² and ${b}², then subtract.`}}
function nextQuestion(){const p=problem(),opts=[p.answer,p.answer+2,Math.max(1,p.answer-3),p.answer+7].sort(()=>Math.random()-.5);shell(games[current][0],`<h2>${games[current][1]}</h2><p>Round ${round+1} of ${total} · Score ${score}</p><div class="question">${p.text}</div><p class="math-hint">💡 ${p.hint}</p><div class="answers">${opts.map(x=>`<button class="answer" data-x="${x}" data-a="${p.answer}">${x}</button>`).join('')}</div><p class="keyboard-hint">⌨️ W A S D chooses an answer</p>`);document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(+b.dataset.x,+b.dataset.a))}
function hasPower(id){return owned.includes(id)}function consumePower(id){owned=owned.filter(x=>x!==id);saveShop();renderShop()}function answer(x,a){if(x!==a&&!hasPower('wild-card')&&!hasPower('extra-life')){score=Math.max(0,score-1);combo=0;document.querySelector('#combo').textContent=combo;toast('Incorrect · combo reset');round++;return setTimeout(()=>round>=total?finish():nextQuestion(),430)}score++;combo++;document.querySelector('#combo').textContent=combo;let multiplier=Math.min(4,1+Math.floor(combo/3));if(hasPower('double-xp'))multiplier*=2;if(hasPower('legend'))multiplier*=2;xp+=20*multiplier;coins+=5*multiplier+(hasPower('coin-magnet')?10:0);$('#xp').textContent=xp;$('#coins').textContent=coins;if(current==='battle')return chooseAttack();toast('Correct · x'+multiplier+' reward combo ✨');round++;setTimeout(()=>round>=total?finish():nextQuestion(),430)}
function chooseAttack(){shell('⚔️ ABILITY READY',`<h2>Choose your attack</h2><div class="scene battle-scene" id="battleArena"><span class="hero-fighter">🧙</span><span class="enemy">👾</span></div><div class="answers"><button class="answer ability" data-spell="fire">1 · 🔥 Fireball</button><button class="answer ability" data-spell="bolt">2 · ⚡ Thunderbolt</button><button class="answer ability" data-spell="wind">3 · 🌪️ Cyclone</button><button class="answer ability" data-spell="shield">4 · 🛡️ Shield Bash</button></div><p class="keyboard-hint">⌨️ Press 1–4 or click an ability · Space = dodge</p>`);document.querySelectorAll('.ability').forEach(b=>b.onclick=()=>cast(b.dataset.spell,b.textContent));document.onkeydown=e=>{const map={'1':'fire','2':'bolt','3':'wind','4':'shield'};if(map[e.key])cast(map[e.key],document.querySelector(`[data-spell="${map[e.key]}"]`).textContent);if(e.code==='Space')toast('Perfect dodge! +10 style points ✨')}}
function cast(spell,label){const arena=$('#battleArena');if(!arena||arena.classList.contains('cast'))return;arena.classList.add('cast',`spell-${spell}`);toast(label+' launched!');setTimeout(()=>{const enemy=arena.querySelector('.enemy');enemy.classList.add('enemy-hit');coins+=20;$('#coins').textContent=coins;toast('Monster defeated! +20 coins 💥');round++;setTimeout(()=>{document.onkeydown=null;round>=total?finish():nextQuestion()},650)},650)}
function finish(){shell('QUEST COMPLETE',`<div class="result"><div class="big">🏆</div><h2>Nice run!</h2><p>You scored <b>${score}/${total}</b> · +${score*20} XP</p><button class="primary" id="again">Play again →</button></div>`);$('#again').onclick=()=>start(current)}
function actionSetup(){const help=current==='racer'?'W accelerates · A/D steer · S brakes':current==='tetris'?'A/D move · W rotate · S drop':'W/A/S/D move through the map';shell(games[current][0],`<h2>${games[current][1]}</h2><canvas id="gameCanvas" width="560" height="300"></canvas><p class="keyboard-hint">⌨️ ${help}</p><button class="primary" id="go">Start game →</button>`);$('#go').onclick=()=>{gameState={x:60,y:240,t:0,won:false,blocks:[],piece:{x:4,y:0,rot:0}};$('#go').remove();keys={};document.onkeydown=e=>{keys[e.key.toLowerCase()]=true;e.preventDefault()};document.onkeyup=e=>keys[e.key.toLowerCase()]=false;raf=requestAnimationFrame(loop)}}
function loop(){const c=$('#gameCanvas'),ctx=c.getContext('2d');gameState.t++;ctx.clearRect(0,0,c.width,c.height);if(current==='racer')race(ctx);else if(current==='board')board(ctx);else tetris(ctx);if(!gameState.won)raf=requestAnimationFrame(loop)}
function race(ctx){ctx.fillStyle='#1c2845';ctx.fillRect(0,0,560,300);ctx.fillStyle='#4d5560';ctx.fillRect(80,0,400,300);ctx.strokeStyle='#fff';ctx.setLineDash([22,20]);ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(280,0);ctx.lineTo(280,300);ctx.stroke();ctx.setLineDash([]);gameState.x+=keys.d?3:keys.a?-3:0;gameState.x=Math.max(95,Math.min(445,gameState.x));gameState.y-=keys.w?2.5:keys.s?-1:0;ctx.font='42px serif';ctx.fillText('🏎️',gameState.x,gameState.y);ctx.fillText('🏁',500,45);ctx.fillStyle='#ff6b5e';ctx.fillRect(18,18,120,12);ctx.fillStyle='#c9f05a';ctx.fillRect(18,18,Math.min(120,gameState.t/8),12);if(gameState.y<35){win('🏁 Finish line!')}}
function board(ctx){ctx.fillStyle='#d9b879';ctx.fillRect(0,0,560,300);ctx.strokeStyle='#86633a';for(let x=0;x<560;x+=56){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,300);ctx.stroke()}for(let y=0;y<300;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(560,y);ctx.stroke()}if(keys.a)gameState.x-=3;if(keys.d)gameState.x+=3;if(keys.w)gameState.y-=3;if(keys.s)gameState.y+=3;gameState.x=Math.max(20,Math.min(530,gameState.x));gameState.y=Math.max(25,Math.min(280,gameState.y));ctx.font='36px serif';ctx.fillText('🧙',gameState.x,gameState.y);ctx.fillText('👾',270,145);ctx.fillText('🏆',500,270);if(gameState.x>470&&gameState.y>230)win('🎁 Treasure found!')}
function tetris(ctx){ctx.fillStyle='#101b38';ctx.fillRect(0,0,560,300);const size=18,ox=190,oy=10;ctx.strokeStyle='#364266';for(let x=0;x<10;x++)for(let y=0;y<15;y++)ctx.strokeRect(ox+x*size,oy+y*size,size,size);if(gameState.t%8===0)gameState.piece.y++;if(keys.a)gameState.piece.x=Math.max(0,gameState.piece.x-1);if(keys.d)gameState.piece.x=Math.min(9,gameState.piece.x+1);if(keys.s)gameState.piece.y=Math.min(14,gameState.piece.y+1);if(keys.w)gameState.piece.rot=(gameState.piece.rot+1)%4;ctx.font='19px serif';ctx.fillText(['🟦','🟨','🟥','🟩'][gameState.piece.rot],ox+gameState.piece.x*size,oy+gameState.piece.y*size+17);ctx.fillStyle='#c9f05a';ctx.font='16px Arial';ctx.fillText('Clear 10 rows to win',18,35);if(gameState.piece.y>=14)win('🧱 Stack complete!')}
function win(msg){gameState.won=true;combo++;if(document.querySelector('#combo'))document.querySelector('#combo').textContent=combo;cancelAnimationFrame(raf);const multiplier=Math.min(4,1+Math.floor(combo/3));xp+=40*multiplier;coins+=20*multiplier;$('#xp').textContent=xp;$('#coins').textContent=coins;toast(msg+' + rewards');setTimeout(()=>shell('LEVEL COMPLETE',`<div class="result"><div class="big">🏆</div><h2>${msg}</h2><button class="primary" id="again">Play again →</button></div>`)||($('#again').onclick=()=>start(current)),700)}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',1300)}
document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>start(b.dataset.game));$('#close').onclick=()=>{$('#backdrop').classList.remove('open');cancelAnimationFrame(raf);document.onkeydown=null;document.onkeyup=null};
document.addEventListener('keydown',e=>{if(!$('#backdrop').classList.contains('open')||document.onkeydown)return;const map={w:0,a:1,s:2,d:3},bs=[...document.querySelectorAll('.answer')];if(map[e.key.toLowerCase()]!==undefined&&bs[map[e.key.toLowerCase()]])bs[map[e.key.toLowerCase()]].click()});


let currentAvatar=localStorage.getItem('mqAvatar')||'🧑‍🚀';const avatarStage=document.querySelector('#avatarStage');if(avatarStage)avatarStage.textContent=currentAvatar;document.querySelectorAll('[data-avatar]').forEach(b=>b.onclick=()=>{currentAvatar=b.dataset.avatar;localStorage.setItem('mqAvatar',currentAvatar);if(avatarStage)avatarStage.textContent=currentAvatar});





document.querySelector('#dailyReward')?.addEventListener('click',()=>{const today=new Date().toDateString();if(localStorage.getItem('mqReward')!==today){coins+=50;xp+=50;localStorage.setItem('mqReward',today);document.querySelector('#coins').textContent=coins;document.querySelector('#xp').textContent=xp;toast('Daily reward claimed! +50 coins +50 XP 🎁')}else toast('Daily reward already claimed — come back tomorrow!')});


const characters=[['Nova','🧑‍🚀'],['Ember','🧝'],['Byte','🤖'],['Luna','🧙‍♀️'],['Bolt','🦸'],['Pixel','👾'],['Rex','🦖'],['Mochi','🐱'],['Koda','🐼'],['Ziggy','🦊'],['Sage','🧑‍🔬'],['Echo','🎧'],['Cosmo','👽'],['Piper','🐧'],['Ranger','🏹'],['Juno','🧚'],['Atlas','🗿'],['Mira','🧜'],['Drift','🛸'],['Sunny','🌞'],['Frost','☃️'],['Cinder','🔥'],['Storm','🌩️'],['Coral','🪸'],['Mint','🌿'],['Quartz','💎'],['Shadow','🥷'],['Blaze','🐉'],['Orbit','🪐'],['Wisp','👻'],['Titan','🦾'],['Bubbles','🐠'],['Dash','🐇'],['Violet','🦄'],['Comet','☄️'],['Maple','🍁'],['Glitch','🕹️'],['Star','⭐'],['Clover','🍀'],['Astra','🌌']];
const powerups=[['extra-life','Extra Life','❤️','Adds one mistake shield',80],['time-boost','Time Boost','⏱️','Adds 15 seconds to races',70],['easy-mode','Focus Lens','🔍','Makes one question easier',65],['double-xp','XP Booster','⚡','Doubles XP for one quest',100],['coin-magnet','Coin Magnet','🧲','Adds bonus coins after wins',90],['shield','Spell Shield','🛡️','Blocks one monster hit',85],['freeze','Time Freeze','❄️','Pauses an arcade timer',75],['turbo','Turbo Shoes','👟','Starts races with a speed boost',95],['heal','First Aid','💚','Restores hospital patient health',60],['hint','Smart Hint','💡','Reveals a useful math clue',45],['streak-save','Streak Save','🔥','Protects your combo once',110],['lucky-roll','Lucky Roll','🎲','Adds three board spaces',55],['magnet','Treasure Radar','🧭','Shows the board treasure path',65],['slow-mo','Slow Motion','🐢','Slows falling blocks',80],['line-clear','Line Clear','💥','Clears one Tetris row',120],['wild-card','Wild Card','🃏','Turns one wrong answer right',130],['focus','Focus Mode','🎯','Removes two wrong choices',90],['combo-star','Combo Star','🌟','Starts a quest with combo 2',100],['revive','Revive Token','🔮','Retry a failed round',75],['spark','Spark Shot','✨','Adds a stronger battle spell',85],['guardian','Guardian Pet','🐲','Pet attacks with you',150],['health-pack','Health Pack','🩹','Restores 25 hospital points',50],['map-key','Map Key','🗝️','Unlocks a shortcut',75],['rocket','Rocket Fuel','🚀','Faster racer acceleration',115],['rainbow','Rainbow Bonus','🌈','Random bonus reward',90],['crown','Champion Crown','👑','Adds a victory badge',200],['portal','Portal Pass','🌀','Skip one board obstacle',100],['brain-chip','Brain Chip','🧠','Adds a small answer timer bonus',85],['gem','Lucky Gem','💠','10% chance of double coins',125],['legend','Legend Aura','🔱','Boosts all rewards',250]];
let owned=JSON.parse(localStorage.getItem('mqOwned')||'[]'),equipped=localStorage.getItem('mqAvatar')||'🧑‍🚀',shopTab='characters';
function saveShop(){localStorage.setItem('mqOwned',JSON.stringify(owned));localStorage.setItem('mqAvatar',equipped);localStorage.setItem('mqCoins',coins);localStorage.setItem('mqXp',xp)}
function renderShop(){const grid=document.querySelector('#shopGrid');if(!grid)return;document.querySelector('#shopCoins').textContent=coins;const list=shopTab==='characters'?characters.map((x,i)=>({id:'char-'+i,name:x[0],icon:x[1],desc:'Playable explorer avatar',price:i<4?0:25+i*5})):powerups.map(x=>({id:x[0],name:x[1],icon:x[2],desc:x[3],price:x[4]}));grid.innerHTML=list.map(x=>{const isOwned=owned.includes(x.id),isEquipped=x.id==='char-'+characters.findIndex(c=>c[1]===equipped);return `<article class="shop-item"><span class="item-icon">${x.icon}</span><h3>${x.name}</h3><p>${x.desc}</p><button data-buy="${x.id}" ${isOwned?'class="owned"':''} ${isOwned&& !isEquipped?'':' '}>${isEquipped?'Equipped':isOwned?'Owned':x.price===0?'Free':'🪙 '+x.price}</button></article>`}).join('');grid.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.buy));}
function buy(id){const charIndex=id.startsWith('char-')?Number(id.slice(5)):-1;const item=charIndex>=0?{price:charIndex<4?0:25+charIndex*5}:powerups.find(x=>x[0]===id);if(owned.includes(id)){if(charIndex>=0){equipped=characters[charIndex][1];localStorage.setItem('mqAvatar',equipped);const av=document.querySelector('#avatarStage');if(av)av.textContent=equipped;toast('Avatar equipped! ✨');renderShop()}else toast('Already in your inventory!');return}const price=charIndex>=0?item.price:item[4];if(coins<price)return toast('Not enough coins yet — keep questing!');coins-=price;owned.push(id);if(charIndex>=0){equipped=characters[charIndex][1];localStorage.setItem('mqAvatar',equipped);const av=document.querySelector('#avatarStage');if(av)av.textContent=equipped}saveShop();document.querySelector('#coins').textContent=coins;toast('Unlocked '+(charIndex>=0?characters[charIndex][0]:item[1])+'! 🎉');renderShop()}
document.querySelector('#shopOpen')?.addEventListener('click',()=>{document.querySelector('#shopBackdrop').classList.add('open');renderShop()});document.querySelector('#shopClose')?.addEventListener('click',()=>document.querySelector('#shopBackdrop').classList.remove('open'));document.querySelectorAll('[data-shop-tab]').forEach(b=>b.onclick=()=>{shopTab=b.dataset.shopTab;document.querySelectorAll('[data-shop-tab]').forEach(x=>x.classList.toggle('active',x===b));renderShop()});
const originalToast=toast;toast=function(t){originalToast(t);saveShop()};


document.querySelector('#coins').textContent=coins;document.querySelector('#xp').textContent=xp;document.querySelector('#shopCoins').textContent=coins;



const baseRenderShop=renderShop;renderShop=function(){baseRenderShop();const inv=document.querySelector('#inventory');if(!inv)return;const ownedChars=owned.map(id=>{if(!id.startsWith('char-'))return null;const c=characters[Number(id.slice(5))];return c?`<button class="${equipped===c[1]?'active':''}" data-equip="${c[1]}">${c[1]} ${c[0]}</button>`:null}).filter(Boolean);const ownedPowers=owned.filter(id=>powerups.some(p=>p[0]===id)).length;inv.innerHTML=`<h3>🎒 My inventory</h3><div class="inventory-list">${ownedChars.length?ownedChars.join(''):'<span class="muted">Buy a character to add it here.</span>'}</div><p class="muted">${ownedPowers} power-up${ownedPowers===1?'':'s'} owned · click a character to equip it.</p>`;inv.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{equipped=b.dataset.equip;localStorage.setItem('mqAvatar',equipped);const av=document.querySelector('#avatarStage');if(av)av.textContent=equipped;renderShop();toast('Character equipped! ✨')})};

characters.push(['Vortex','🌀'],['Magma','🌋'],['Finch','🐦'],['Sparky','⚡'],['Moss','🍄'],['Glacier','🧊'],['Rocket','🚀'],['Rune','🔮'],['Honey','🐝'],['Mantis','🦗']);powerups.push(['overdrive','Overdrive','💨','Double arcade movement speed',140],['combo-lock','Combo Lock','🔒','Combo cannot reset once',160],['answer-bank','Answer Bank','🏦','Stores one correct answer',70],['teleport','Teleport Step','🛼','Jump to the next checkpoint',125],['boss-slayer','Boss Slayer','⚔️','Extra damage against bosses',180],['perfect-pitch','Perfect Pitch','🎵','Adds bonus XP for a streak',95],['study-buddy','Study Buddy','📚','Shows a worked example',60],['energy-drink','Energy Drink','🥤','Restores arcade energy',55],['golden-dice','Golden Dice','🎰','Doubles a board roll',145],['time-warp','Time Warp','🕰️','Adds a second chance timer',135]);
